[package]
name = "vtstats-search"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "lib.rs"

[dependencies]
meilisearch-sdk = "0.27"
vtstats-database = { path = "../vtstats-database" }
chrono = { version = "0.4.26", default-features = false, features = ["serde"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version = "1.0.97", features = ["arbitrary_precision"] }
serde_with = "3.0.0"